#!/usr/bin/env sh

INPUT=$1; shift
OUTPUT=$1; shift

# compile ES6 code to ES5 compat code for Webpack / Node.js
babel \
  "$INPUT" \
  --out-file "$OUTPUT" \
  --source-maps \
  --presets es2015 \
  --plugins transform-runtime,syntax-async-functions,transform-async-to-generator,transform-dirname-filename \
  "$@"
