#!/usr/bin/env sh

INPUT=$1; shift
OUTPUT=$1; shift

ARGS=
PRESETS=es2015
PLUGINS=transform-runtime,syntax-async-functions,transform-async-to-generator,transform-dirname-filename,add-module-exports,transform-object-rest-spread

while [ "x$1" != "x" ]
  do
  case "$1" in
    --preset)
      shift
      PRESETS="$PRESETS,$1"
      ;;
    --plugin)
      shift
      PLUGINS="$PLUGINS,$1"
      ;;
    *)
      ARGS="$ARGS "$1""
      ;;
    esac
  shift
done

# compile ES6 code to ES5 compat code for Webpack / Node.js
babel \
  "$INPUT" \
  --out-file "$OUTPUT" \
  --source-maps \
  --presets "$PRESETS" \
  --plugins "$PLUGINS" \
  $ARGS
